kind = "web"
previewPath = "/"
title = "Кухни на заказ"
version = "1.0.0"
id = "artifacts/kuhni-na-zakaz"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25952

[services.development]
run = "pnpm --filter @workspace/kuhni-na-zakaz run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kuhni-na-zakaz", "run", "build" ]
run = "pnpm --filter @workspace/kuhni-na-zakaz run start"

[services.env]
PORT = "25952"
BASE_PATH = "/"
